Modif CI at Wed Mar  9 14:40:15 CET 2022

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -151,24 +151,23 @@ jobs:
             echo "-- ${arrIN[0]} --"
             echo "---------------------------------"
             git checkout ${arrIN[0]}
-            p4 status
+            #p4 status
             p4 reconcile
             opened_files_nb=$(p4 opened | wc -l)
             #echo "OPENED : ${opened_files_nb}"
             if [ ${opened_files_nb} -gt 0 ]
             then 
               echo "p4 submit -d \"${message}\""
-            fi
-            
-            opened_files_nb=$(p4 opened | wc -l)
-            #echo "OPENED : ${opened_files_nb}"
-            if [ ${opened_files_nb} -gt 0 ]
-            then
-              echo "ABORTING, there are still opened files after p4 submit:"
-              p4 opened 
-              echo "REVERTING LAST CHANGES"
-              p4 revert ./...
-              exit 1
+              opened_files_nb=$(p4 opened | wc -l)
+              #echo "OPENED : ${opened_files_nb}"
+              if [ ${opened_files_nb} -gt 0 ]
+              then
+                echo "ABORTING, there are still opened files after p4 submit:"
+                p4 opened 
+                echo "REVERTING LAST CHANGES"
+                p4 revert ./...
+                exit 1
+              fi
             fi
 
           done < ${{ env.COMMIT_LIST_FILE }}
