TOSYNC Testing managing fails

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -101,7 +101,7 @@ jobs:
             SCRIPT_OPT='--force_sync'
           else
             export RET=`p4 changes -l -c $P4CLIENT -s submitted -m 1 | head -3 | tail -1 | grep "^\s*\[ GIT INTEG \]" | sed -e "s/^.*\[ GIT INTEG \] //;s/ .*$//"`; 
-            if [ -z $RET ]
+            if [ -z $RET ] || [ "$RET" == "" ]
             then 
               exit 1
             else 
@@ -211,15 +211,15 @@ jobs:
             IFS='||'; arrIN=($LINE); unset IFS;
             message="[ GIT INTEG ] ${arrIN[0]} - ${arrIN[2]}"
             p4 submit -d "$message"
-            return_value=$?
-            if [ $return_value -eq 0 ]
-            then 
-              echo "Submit done"
-            else
-              echo "Error while submiting (1st run)"
-              ### TO BE CONTINUED (email)
-              exit 1
-            fi
+            # return_value=$?
+            # if [ $return_value -eq 0 ]
+            # then 
+            #   echo "Submit done"
+            # else
+            #   echo "Error while submiting (1st run)"
+            #   ### TO BE CONTINUED (email)
+            #   exit 1
+            # fi
 
           else
 
@@ -254,77 +254,76 @@ jobs:
 
             else 
               # Exit 1 not found LAST_KNOW_INTEG_COMMIT
-              echo "Error cannot find a last known integrate commit in $P4REPOPERFORCE repository"
-              #### SEND EMAIL ####
+              # echo "Error cannot find a last known integrate commit in $P4REPOPERFORCE repository"
               exit 1
             fi
 
           fi
 
-      # - name: Managing step execution
-      #   if: ${{ always() }}
-      #   run: |
-      #     CONTINUE=1
-      #     echo -e "\n#### STATUS_STEP_PERFORCE_LAST_KNOWN_GIT_COMMIT ###"
-      #     echo "STATUS : $STATUS_STEP_PERFORCE_LAST_KNOWN_GIT_COMMIT"
-      #     if [ "$STATUS_STEP_PERFORCE_LAST_KNOWN_GIT_COMMIT" == 0 ]
-      #     then
-      #       echo -e "[ \033[32;2;1mOK\033[0m ]" 
-      #       echo "  EMAIL MUST BE SENT"
-      #       echo "  MSG : $MSG_STEP_PERFORCE_LAST_KNOWN_GIT_COMMIT"
-      #       CONTINUE=0
-      #     else
-      #       echo -e "[ \033[31;2;1mFAILED\033[0m ]"
-      #     fi
+      - name: Managing step execution
+        if: ${{ always() }}
+        run: |
+          CONTINUE=1
+          echo -e "\n#### STATUS_STEP_PERFORCE_LAST_KNOWN_GIT_COMMIT ###"
+          echo "STATUS : $STATUS_STEP_PERFORCE_LAST_KNOWN_GIT_COMMIT"
+          if [ "$STATUS_STEP_PERFORCE_LAST_KNOWN_GIT_COMMIT" == 0 ]
+          then
+            echo -e "[ \033[32;2;1mOK\033[0m ]" 
+            echo "  EMAIL MUST BE SENT"
+            echo "  MSG : $MSG_STEP_PERFORCE_LAST_KNOWN_GIT_COMMIT"
+            CONTINUE=0
+          else
+            echo -e "[ \033[31;2;1mFAILED\033[0m ]"
+          fi
 
-      #     if [ "$CONTINUE" == 1 ]
-      #     then
-      #       echo -e "\n#### STATUS_STEP_SUBMIT_TMP_SYNC_REPO ###"
-      #       echo "STATUS : $STATUS_STEP_SUBMIT_TMP_SYNC_REPO"
-      #       if [ "$STATUS_STEP_SUBMIT_TMP_SYNC_REPO" == 0 ]
-      #       then 
-      #         echo -e "[ \033[32;2;1mOK\033[0m ]" 
-      #         echo "  EMAIL MUST BE SENT"
-      #         echo "  MSG : $MSG_STEP_SUBMIT_TMP_SYNC_REPO ($INFO_STEP_SUBMIT_TMP_SYNC_REPO)"
-      #       CONTINUE=0
-      #       else
-      #         echo -e "[ \033[31;2;1mFAILED\033[0m ]"
-      #       fi
-      #     fi
+          if [ "$CONTINUE" == 1 ]
+          then
+            echo -e "\n#### STATUS_STEP_SUBMIT_TMP_SYNC_REPO ###"
+            echo "STATUS : $STATUS_STEP_SUBMIT_TMP_SYNC_REPO"
+            if [ "$STATUS_STEP_SUBMIT_TMP_SYNC_REPO" == 0 ]
+            then 
+              echo -e "[ \033[32;2;1mOK\033[0m ]" 
+              echo "  EMAIL MUST BE SENT"
+              echo "  MSG : $MSG_STEP_SUBMIT_TMP_SYNC_REPO ($INFO_STEP_SUBMIT_TMP_SYNC_REPO)"
+            CONTINUE=0
+            else
+              echo -e "[ \033[31;2;1mFAILED\033[0m ]"
+            fi
+          fi
 
-      #     if [ "$CONTINUE" == 1 ]
-      #     then
-      #       echo -e "\n#### STATUS_STEP_PERFORCE_LAST_KNOWN_INTEGRATED_COMMIT ###"
-      #       echo "STATUS : $STATUS_STEP_PERFORCE_LAST_KNOWN_INTEGRATED_COMMIT"
-      #       if [ "$STATUS_STEP_PERFORCE_LAST_KNOWN_INTEGRATED_COMMIT" == 0 ]
-      #       then 
-      #         echo -e "[ \033[32;2;1mOK\033[0m ]" 
-      #         echo "  EMAIL MUST BE SENT"
-      #         echo "  MSG : $MSG_STEP_PERFORCE_LAST_KNOWN_INTEGRATED_COMMIT"
-      #         CONTINUE=0
-      #       else
-      #         echo -e "[ \033[31;2;1mFAILED\033[0m ]"
-      #       fi
-      #     fi
+          if [ "$CONTINUE" == 1 ]
+          then
+            echo -e "\n#### STATUS_STEP_PERFORCE_LAST_KNOWN_INTEGRATED_COMMIT ###"
+            echo "STATUS : $STATUS_STEP_PERFORCE_LAST_KNOWN_INTEGRATED_COMMIT"
+            if [ "$STATUS_STEP_PERFORCE_LAST_KNOWN_INTEGRATED_COMMIT" == 0 ]
+            then 
+              echo -e "[ \033[32;2;1mOK\033[0m ]" 
+              echo "  EMAIL MUST BE SENT"
+              echo "  MSG : $MSG_STEP_PERFORCE_LAST_KNOWN_INTEGRATED_COMMIT"
+              CONTINUE=0
+            else
+              echo -e "[ \033[31;2;1mFAILED\033[0m ]"
+            fi
+          fi
 
-      #     if [ "$CONTINUE" == 1 ] 
-      #     then
-      #       echo -e "\n"#### STATUS_STEP_SUBMIT_INTEGRATE_REPO ###"
-      #       echo "STATUS : $STATUS_STEP_SUBMIT_INTEGRATE_REPO"
-      #       if [ "$STATUS_STEP_SUBMIT_INTEGRATE_REPO" == 0 ]
-      #       then 
-      #         echo -e "[ \033[32;2;1mOK\033[0m ]" 
-      #         echo "  EMAIL MUST BE SENT"
-      #         echo "  MSG : $MSG_STEP_SUBMIT_INTEGRATE_REPO ($INFO_STEP_SUBMIT_INTEGRATE_REPO)"
+          if [ "$CONTINUE" == 1 ] 
+          then
+            echo -e "\n"#### STATUS_STEP_SUBMIT_INTEGRATE_REPO ###"
+            echo "STATUS : $STATUS_STEP_SUBMIT_INTEGRATE_REPO"
+            if [ "$STATUS_STEP_SUBMIT_INTEGRATE_REPO" == 0 ]
+            then 
+              echo -e "[ \033[32;2;1mOK\033[0m ]" 
+              echo "  EMAIL MUST BE SENT"
+              echo "  MSG : $MSG_STEP_SUBMIT_INTEGRATE_REPO ($INFO_STEP_SUBMIT_INTEGRATE_REPO)"
 
-      #         export P4CLIENT=$(echo "${{secrets.P4USER}}_${{ github.repository }}_integrate_perforce" | tr '/' '_')
-      #         echo "---------"
-      #         p4 opened
-      #         p4 changes -s pending -c $P4CLIENT
-      #         echo "---------"
+              export P4CLIENT=$(echo "${{secrets.P4USER}}_${{ github.repository }}_integrate_perforce" | tr '/' '_')
+              echo "---------"
+              p4 opened
+              p4 changes -s pending -c $P4CLIENT
+              echo "---------"
 
-      #         CONTINUE=0
-      #       else
-      #         echo -e "[ \033[31;2;1mFAILED\033[0m ]"
-      #       fi
-      #     fi
+              CONTINUE=0
+            else
+              echo -e "[ \033[31;2;1mFAILED\033[0m ]"
+            fi
+          fi
