CI workflow

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -85,64 +85,64 @@ jobs:
           echo -e "P4USER=$P4USER\nP4PORT=$P4PORT\nP4CLIENT=$P4CLIENT" > .p4config
 
 
-      # # Get all unsynced commit since last good one
-      # # If we never meet the last known commit on perforce we abort, that could mean there are more commits to into account
-      # # At WS creation we use the dedicated --force_sync option to accept submiting event if perforce_last_commit has not been found
-      # # so if this specific case fails, think to delete perforce client before re-running
-      # - name: Get all unsynced commit since last good one
-      #   run: |
-      #     sync_git_2_perforce.py \
-      #       --git_api_url ${{ github.api_url }} \
-      #       --git_repo ${{ github.repository }} \
-      #       --git_user ${{ github.actor }} \
-      #       --git_token ${{ secrets.GITHUB_TOKEN }} \
-      #       --interval_check "${{ env.DATE_MIN_CHECK_COMMITS }}" \
-      #       --output_file ${{ env.COMMIT_LIST_FILE }} \
-      #       ${{ steps.perforce.outputs.sync_option }} \
-      #       --current_commit ${{github.sha}} 
+      # Get all unsynced commit since last good one
+      # If we never meet the last known commit on perforce we abort, that could mean there are more commits to into account
+      # At WS creation we use the dedicated --force_sync option to accept submiting event if perforce_last_commit has not been found
+      # so if this specific case fails, think to delete perforce client before re-running
+      - name: Get all unsynced commit since last good one
+        run: |
+          sync_git_2_perforce.py \
+            --git_api_url ${{ github.api_url }} \
+            --git_repo ${{ github.repository }} \
+            --git_user ${{ github.actor }} \
+            --git_token ${{ secrets.GITHUB_TOKEN }} \
+            --interval_check "${{ env.DATE_MIN_CHECK_COMMITS }}" \
+            --output_file ${{ env.COMMIT_LIST_FILE }} \
+            ${{ steps.perforce.outputs.sync_option }} \
+            --current_commit ${{github.sha}} 
 
-      # # Create/Upgrade local git repo
-      # - uses: actions/checkout@v2
-      #   with:
-      #     path: ${{ steps.set_workdir.outputs.value }}
-      #     clean: 'false'
-      #     lfs: 'true'
-      # - name: Unshallow the git log, else we won't be able to checkout commits 
-      #   working-directory: ${{ steps.set_workdir.outputs.value }}
-      #   run: git fetch --unshallow
+      # Create/Upgrade local git repo
+      - uses: actions/checkout@v2
+        with:
+          path: ${{ steps.set_workdir.outputs.value }}
+          clean: 'false'
+          lfs: 'true'
+      - name: Unshallow the git log, else we won't be able to checkout commits 
+        working-directory: ${{ steps.set_workdir.outputs.value }}
+        run: git fetch --unshallow
 
-      # ## For each commit found: get git files, p4 reconcile and submit
-      # # If some file are still opened after submit, abort
-      # - name: Upgrade perforce for each git commit found
-      #   working-directory: ${{ steps.set_workdir.outputs.value }}
-      #   run: |
-      #     git config --global advice.detachedHead false
-      #     while read LINE
-      #     do
-      #       IFS='||'; arrIN=($LINE); unset IFS;
-      #       message="[ GIT INTEG ] ${arrIN[0]} - ${arrIN[2]}"
-      #       echo "---------------------------------"
-      #       echo "-- ${arrIN[0]} --"
-      #       echo "---------------------------------"
-      #       git checkout ${arrIN[0]}
-      #       #p4 status
-      #       p4 reconcile
-      #       opened_files_nb=$(p4 opened | wc -l)
-      #       #echo "OPENED : ${opened_files_nb}"
-      #       if [ ${opened_files_nb} -gt 0 ]
-      #       then 
-      #         p4 submit -d "${message}"
-      #         return_value=$?
-      #         if [ $return_value -eq 0 ]
-      #         then 
-      #           echo "Submit done"
-      #         else
-      #           echo "Error while submiting"
-      #           exit 1
-      #         fi
-      #       fi
+      ## For each commit found: get git files, p4 reconcile and submit
+      # If some file are still opened after submit, abort
+      - name: Upgrade perforce for each git commit found
+        working-directory: ${{ steps.set_workdir.outputs.value }}
+        run: |
+          git config --global advice.detachedHead false
+          while read LINE
+          do
+            IFS='||'; arrIN=($LINE); unset IFS;
+            message="[ GIT INTEG ] ${arrIN[0]} - ${arrIN[2]}"
+            echo "---------------------------------"
+            echo "-- ${arrIN[0]} --"
+            echo "---------------------------------"
+            git checkout ${arrIN[0]}
+            #p4 status
+            p4 reconcile
+            opened_files_nb=$(p4 opened | wc -l)
+            #echo "OPENED : ${opened_files_nb}"
+            if [ ${opened_files_nb} -gt 0 ]
+            then 
+              p4 submit -d "${message}"
+              return_value=$?
+              if [ $return_value -eq 0 ]
+              then 
+                echo "Submit done"
+              else
+                echo "Error while submiting"
+                exit 1
+              fi
+            fi
 
-      #     done < ${{ env.COMMIT_LIST_FILE }}
+          done < ${{ env.COMMIT_LIST_FILE }}
 
 
       # # Create a WS to integration (and merge on the fly) the temporary repo (sync_git_perforce) to the final destination
