TOSYNC CI workflow

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -78,7 +78,13 @@ jobs:
 
           export SCRIPT_OPT=''
           export RET=`p4 changes -l -c $P4CLIENT -s submitted -m 1 | head -3 | tail -1 | grep "^\s*\[ GIT INTEG \]" | sed -e "s/^.*\[ GIT INTEG \] //;s/ .*$//"`; 
-          if [ -z $RET ]; then SCRIPT_OPT='--perforce_last_commit xxxxxxxxxxxxxxxxxx'; else SCRIPT_OPT="--perforce_last_commit $RET"; fi
+          if [ -z $RET ]
+          then 
+            SCRIPT_OPT=''
+            exit 1
+            echo "Could not find any commit reference in perforce submission, if the remote perforce WS is empty (creation), the SCRIPT_OPTION should be set to --force_sync  and exit 1 commented, and run once like this"
+          else 
+            SCRIPT_OPT="--perforce_last_commit $RET"; fi
 
           echo "::set-output name=sync_option::$SCRIPT_OPT"
 
@@ -145,35 +151,35 @@ jobs:
           done < ${{ env.COMMIT_LIST_FILE }}
 
 
-      # # Create a WS to integration (and merge on the fly) the temporary repo (sync_git_perforce) to the final destination
-      # # Both views are declared
-      # - name: Create/Update integrate workspace
-      #   working-directory: ${{ env.INTEGRATE_WS }}
-      #   run: |
-      #     echo $P4PASSWD | p4 login
-      #     export P4CLIENT=$(echo "${{secrets.P4USER}}_${{ github.repository }}_integrate_perforce" | tr '/' '_')
-      #     # echo "P4CLIENT=$P4CLIENT" >> $GITHUB_ENV
-      #     echo "P4CLIENT=$P4CLIENT"
-      #     pwd
-      #     if ! p4 client -o -t $P4CLIENT > /dev/null 2>&1; then 
-      #       echo "Creating workspace $P4CLIENT (1st time run)"
-      #       echo "
-      #     Client: $P4CLIENT
-      #     Owner:  servbot
-      #     Root:   $PWD
-      #     Options:        noallwrite noclobber nocompress unlocked nomodtime normdir
-      #     SubmitOptions:  submitunchanged
-      #     LineEnd:        local
-      #     View:
-      #       $P4REPOSYNCPERFORCE/... //$P4CLIENT/sync_perforce/...
-      #       $P4REPOPERFORCE/... //$P4CLIENT/dest_perforce/...
-      #       -$P4REPOPERFORCE/.p4config //$P4CLIENT/.p4config
-      #       " | p4 client -i;
-      #     fi
+      # Create a WS to integration (and merge on the fly) the temporary repo (sync_git_perforce) to the final destination
+      # Both views are declared
+      - name: Create/Update integrate workspace
+        working-directory: ${{ env.INTEGRATE_WS }}
+        run: |
+          echo $P4PASSWD | p4 login
+          export P4CLIENT=$(echo "${{secrets.P4USER}}_${{ github.repository }}_integrate_perforce" | tr '/' '_')
+          # echo "P4CLIENT=$P4CLIENT" >> $GITHUB_ENV
+          echo "P4CLIENT=$P4CLIENT"
+          pwd
+          if ! p4 client -o -t $P4CLIENT > /dev/null 2>&1; then 
+            echo "Creating workspace $P4CLIENT (1st time run)"
+            echo "
+          Client: $P4CLIENT
+          Owner:  servbot
+          Root:   $PWD
+          Options:        noallwrite noclobber nocompress unlocked nomodtime normdir
+          SubmitOptions:  submitunchanged
+          LineEnd:        local
+          View:
+            $P4REPOSYNCPERFORCE/... //$P4CLIENT/sync_perforce/...
+            $P4REPOPERFORCE/... //$P4CLIENT/dest_perforce/...
+            -$P4REPOPERFORCE/.p4config //$P4CLIENT/.p4config
+            " | p4 client -i;
+          fi
 
-      #     # p4 sync
-      #     echo -e "P4USER=$P4USER\nP4PORT=$P4PORT\nP4CLIENT=$P4CLIENT" > .p4config
+          # p4 sync
+          echo -e "P4USER=$P4USER\nP4PORT=$P4PORT\nP4CLIENT=$P4CLIENT" > .p4config
 
-      #     # Getting the last submited changelist
+          # Getting the last submited changelist
 
 
