TOSYNC CI workflow

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -28,39 +28,36 @@ jobs:
       P4PORT: ${{secrets.P4PORT}}
       P4USER: ${{secrets.P4USER}}
       P4PASSWD: ${{secrets.P4PASSWD}}
-      P4CLIENT: "servbot_commoncontainer_sync_git_perforce"
+      P4REPOSYNCPERFORCE: "//depot/Radioss/pfake_oss_mainline"
+      P4REPOPERFORCE: "//depot/Radioss/pfake_oss_mainline_final"
       DATE_MIN_CHECK_COMMITS: "7 days ago"
       COMMIT_LIST_FILE: /tmp/commits_list
+      INTEGRATE_WS: integrate_perforce
 
     steps:
 
-      - name: Check env dir 
-        run: |
-          echo "Env dir is ${{inputs.working_directory}}"
-
-
       # Set the working dir suffixed with branch name
       - uses: haya14busa/action-cond@v1
-        id: condval
+        id: set_workdir
         with:
           cond: ${{ github.base_ref == '' }}
           if_true: ${{github.ref_name}}
           if_false: ${{github.base_ref}}
-      - name: Use conditional value
-        run: |
-          echo "working-directory=${{ steps.condval.outputs.value }}" >> $GITHUB_ENV
 
-      - name: Create branch oriented WS directory
+      - name: Create branch oriented WS directory & integration WS
         run: |
-          mkdir -p ${{env.working-directory}}
+          mkdir -p ${{ steps.set_workdir.outputs.value }} $INTEGRATE_WS
 
-      # Create and update perforce WS, commercial files should not be present in this WS
-      - name: Create/Update perforce directory
-        working-directory: ${{env.working-directory}}
+      # Create a WS to sync git changes on a temporary repo (sync_git_perforce)
+      - name: Create/Update sync_git_perforce workspace
+        working-directory: ${{ steps.set_workdir.outputs.value }}
+        id: perforce
         run: |
           echo $P4PASSWD | p4 login
+          export P4CLIENT=$(echo "${{secrets.P4USER}}_${{ github.repository }}_sync_git_perforce" | tr '/' '_')
+          echo "P4CLIENT=$P4CLIENT" >> $GITHUB_ENV
           if ! p4 client -o -t $P4CLIENT > /dev/null 2>&1; then 
-            echo "Creating workspace $P4CLIENT (1st time run ?)"
+            echo "Creating workspace $P4CLIENT (1st time run)"
             echo "
           Client: $P4CLIENT
           Owner:  servbot
@@ -69,24 +66,29 @@ jobs:
           SubmitOptions:  submitunchanged
           LineEnd:        local
           View:
-            //depot/Radioss/pfake_oss_mainline/... //$P4CLIENT/...
-            -//depot/Radioss/pfake_oss_mainline/.git/... //$P4CLIENT/.git/...
-            -//depot/Radioss/pfake_oss_mainline/.github/... //$P4CLIENT/.github/...
-            -//depot/Radioss/pfake_oss_mainline/C/... //$P4CLIENT/C/...
+            $P4REPOSYNCPERFORCE/... //$P4CLIENT/...
+            $P4REPOSYNCPERFORCE/C/... //$P4CLIENT/C/...
+            -$P4REPOSYNCPERFORCE/.git/... //$P4CLIENT/.git/...
+            -$P4REPOSYNCPERFORCE/.github/... //$P4CLIENT/.github/...
+            -$P4REPOSYNCPERFORCE/.p4config //$P4CLIENT/.p4config
             " | p4 client -i;
           fi
+
           p4 sync
 
-      # Get perforce last synced commit
-      - name: Get perforce last synced commit
-        id: found_perforce_infos
-        working-directory: ${{env.working-directory}}
-        run: |
-          pwd
-          echo "::set-output name=last_commit_on_perforce::$(p4 changes -l -m 1 -s submitted ./...  | head -3 | tail -1 | sed -e "s/^.*\[ GIT INTEG \] //;s/ .*$//")"
+          export SCRIPT_OPT=''
+          export RET=`p4 changes -l -c $P4CLIENT -s submitted -m 1 | head -3 | tail -1 | grep "^\s*\[ GIT INTEG \]" | sed -e "s/^.*\[ GIT INTEG \] //;s/ .*$//"`; 
+          if [ -z $RET ]; then SCRIPT_OPT='--force_sync'; else SCRIPT_OPT="--perforce_last_commit $RET"; fi
+
+          echo "::set-output name=sync_option::$SCRIPT_OPT"
+
+          echo -e "P4USER=$P4USER\nP4PORT=$P4PORT\nP4CLIENT=$P4CLIENT" > .p4config
+
 
       # Get all unsynced commit since last good one
       # If we never meet the last known commit on perforce we abort, that could mean there are more commits to into account
+      # At WS creation we use the dedicated --force_sync option to accept submiting event if perforce_last_commit has not been found
+      # so if this specific case fails, think to delete perforce client before re-running
       - name: Get all unsynced commit since last good one
         run: |
           sync_git_2_perforce.py \
@@ -95,23 +97,24 @@ jobs:
             --git_user ${{ github.actor }} \
             --git_token ${{ secrets.GITHUB_TOKEN }} \
             --interval_check "${{ env.DATE_MIN_CHECK_COMMITS }}" \
-            --perforce_last_commit ${{ steps.found_perforce_infos.outputs.last_commit_on_perforce }} \
             --output_file ${{ env.COMMIT_LIST_FILE }} \
-            --current_commit ${{github.sha}}
+            ${{ steps.perforce.outputs.sync_option }} \
+            --current_commit ${{github.sha}} 
 
       # Create/Upgrade local git repo
       - uses: actions/checkout@v2
         with:
-          path: ${{env.working-directory}}
+          path: ${{ steps.set_workdir.outputs.value }}
           clean: 'false'
+          lfs: 'true'
       - name: Unshallow the git log, else we won't be able to checkout commits 
-        working-directory: ${{env.working-directory}}
+        working-directory: ${{ steps.set_workdir.outputs.value }}
         run: git fetch --unshallow
 
       ## For each commit found: get git files, p4 reconcile and submit
       # If some file are still opened after submit, abort
       - name: Upgrade perforce for each git commit found
-        working-directory: ${{env.working-directory}}
+        working-directory: ${{ steps.set_workdir.outputs.value }}
         run: |
           git config --global advice.detachedHead false
           while read LINE
@@ -129,16 +132,48 @@ jobs:
             if [ ${opened_files_nb} -gt 0 ]
             then 
               p4 submit -d "${message}"
-              opened_files_nb=$(p4 opened | wc -l)
-              #echo "OPENED : ${opened_files_nb}"
-              if [ ${opened_files_nb} -gt 0 ]
-              then
-                echo "ABORTING, there are still opened files after p4 submit:"
-                p4 opened 
-                echo "REVERTING LAST CHANGES"
-                p4 revert ./...
+              return_value=$?
+              if [ $return_value -eq 0 ]
+              then 
+                echo "Submit done"
+              else
+                echo "Error while submiting"
                 exit 1
               fi
             fi
 
           done < ${{ env.COMMIT_LIST_FILE }}
+
+
+      # # Create a WS to integration (and merge on the fly) the temporary repo (sync_git_perforce) to the final destination
+      # # Both views are declared
+      # - name: Create/Update integrate workspace
+      #   working-directory: ${{ env.INTEGRATE_WS }}
+      #   run: |
+      #     echo $P4PASSWD | p4 login
+      #     export P4CLIENT=$(echo "${{secrets.P4USER}}_${{ github.repository }}_integrate_perforce" | tr '/' '_')
+      #     # echo "P4CLIENT=$P4CLIENT" >> $GITHUB_ENV
+      #     echo "P4CLIENT=$P4CLIENT"
+      #     pwd
+      #     if ! p4 client -o -t $P4CLIENT > /dev/null 2>&1; then 
+      #       echo "Creating workspace $P4CLIENT (1st time run)"
+      #       echo "
+      #     Client: $P4CLIENT
+      #     Owner:  servbot
+      #     Root:   $PWD
+      #     Options:        noallwrite noclobber nocompress unlocked nomodtime normdir
+      #     SubmitOptions:  submitunchanged
+      #     LineEnd:        local
+      #     View:
+      #       $P4REPOSYNCPERFORCE/... //$P4CLIENT/sync_perforce/...
+      #       $P4REPOPERFORCE/... //$P4CLIENT/dest_perforce/...
+      #       -$P4REPOPERFORCE/.p4config //$P4CLIENT/.p4config
+      #       " | p4 client -i;
+      #     fi
+
+      #     # p4 sync
+      #     echo -e "P4USER=$P4USER\nP4PORT=$P4PORT\nP4CLIENT=$P4CLIENT" > .p4config
+
+      #     # Getting the last submited changelist
+
+
